version: "3"

services:
  btwattch-collector:
    restart: always
    build: .
    #privileged: true
    security_opt:
      - apparmor=unconfined
    network_mode: host
    cap_drop:
      - ALL
    #cap_add:
    #  - NET_ADMIN
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    environment:
      - INFLUXDB_HOST
      - INFLUXDB_ORG
      - INFLUXDB_BUCKET
      - INFLUXDB_TOKEN
